language: r
warnings_are_errors: false
sudo: required

r_packages:
 - testthat
 - covr
 - ggplot2
 - ggrepel
 - randomForest
 - ranger

after_success:
 - Rscript -e 'library(covr); codecov()'

notifications:
  email:
   on_success: change
   on_failure: change


