language: r
warnings_are_errors: false
sudo: true
dist: trusty
group: deprecated-2017Q4


r:
 - release
 - devel

r_packages:
 - devtools
 - testthat
 - covr
 - randomForest
 - ranger

after_success:
 - Rscript -e 'library(covr); codecov()'

notifications:
  email:
   on_success: change
   on_failure: change
