# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nCm_ratio2 <- function(n1, m1, n2, m2) {
    .Call('_forestControl_nCm_ratio2', PACKAGE = 'forestControl', n1, m1, n2, m2)
}

prob_Ckt2 <- function(Ft, N, Fn, K, k) {
    .Call('_forestControl_prob_Ckt2', PACKAGE = 'forestControl', Ft, N, Fn, K, k)
}

prob_Cft2 <- function(Ft, N, Fn) {
    .Call('_forestControl_prob_Cft2', PACKAGE = 'forestControl', Ft, N, Fn)
}

