# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nCm_ratio2 <- function(n1, m1, n2, m2) {
    .Call('_forestControl_nCm_ratio2', PACKAGE = 'forestControl', n1, m1, n2, m2)
}

prob_Ckt2 <- function(Ft, N, Fn, K, k) {
    .Call('_forestControl_prob_Ckt2', PACKAGE = 'forestControl', Ft, N, Fn, K, k)
}

prob_Cft2 <- function(Ft, Fn) {
    .Call('_forestControl_prob_Cft2', PACKAGE = 'forestControl', Ft, Fn)
}

SF_FPR <- function(k, Ft, Fn, Tr, K) {
    .Call('_forestControl_SF_FPR', PACKAGE = 'forestControl', k, Ft, Fn, Tr, K)
}

fpr_fs_calc2 <- function(k, Ft, Fn, Tr, K) {
    .Call('_forestControl_fpr_fs_calc2', PACKAGE = 'forestControl', k, Ft, Fn, Tr, K)
}

testFun <- function(a) {
    .Call('_forestControl_testFun', PACKAGE = 'forestControl', a)
}

test <- function(a) {
    .Call('_forestControl_test', PACKAGE = 'forestControl', a)
}

